version: "3.7"

services:
  
  portal-ui:
    build: ./context
    # Build the image with name and tag
    image: portal-ui:1.0
    hostname: portal-ui
    container_name: portal-ui
    # Avoid accidentally creating zombie processes
    init: true
    # Specifying a restart policy to avoid downtime
    restart: always
    volumes:
      # Mount the app config to container in order to keep it outside of the image
      - "./context/instance/app.conf:/app/instance/app.conf"
    networks:
      - gateway_hubmap

networks:
  # This is the network created by gateway to enable communicaton between multiple docker-compose projects
  gateway_hubmap:
    external: true