version: "3.7"

services:

  portal-ui:
    build: ../context
    volumes:
      - "../context/instance/app.conf:/app/instance/app.conf"
    ports:
      - "80:80"

  nginx:
    # In production, the NGINX reverse proxy is provided by the gateway.
    image: nginx:1.17.6
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      # Map port 5000 on localhost to 80 on container
      - "5000:80"
