version: "3.7"

services:

  portal-ui:
    hostname: portal-ui
    container_name: portal-ui
    image: hubmap/portal-ui:latest

    volumes:
      # Mount the app config in container to keep it outside the container.
      - "../context/instance/app.conf:/app/instance/app.conf"
      # Mount the logs so they are visible outside the container.
      - "../log/:/var/log/portal-ui/"

    # Avoid accidentally creating zombie processes
    init: true

    # Specifying a restart policy to avoid downtime
    restart: always

    networks:
      - gateway_hubmap

networks:
  # This is the network created by gateway to enable communicaton between multiple docker-compose projects
  gateway_hubmap:
    external: true
