name: Chromatic

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install --prefix context

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: context
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
