name: 🌲 Cypress CI

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  build:

    # Available versions:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # TODO: Only being used to serve static assets: Could use node instead?
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: Set up Node 12.16.3
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.3'
        cache: 'npm'
        cache-dependency-path: context/package-lock.json
   
    - name: Install node dependencies
      run: npm ci --prefix context

    - name: Set up git config to make dev-start.sh happy
      run: git config --global submodule.recurse true

    - name: Run test script
      run: ./test-cypress.sh
      env:
        GH_ACTIONS_BRANCH: ${{ github.ref }}
        GH_ACTIONS: true
