name: ⬡ Node CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  build:
    # Available versions:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: pnpm/action-setup@v2
        with:
          version: 8.8.0
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
          cache-dependency-path: context/pnpm-lock.yaml
      - run: pnpm --version

      - name: Install node dependencies
        run: pnpm i --frozen-lockfile --dir context

      - name: Run test script
        run: etc/test/test-node.sh
