name: Portal CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install python main dependencies
      run: pip install -r context/requirements.txt

    - name: Install python dev dependencies
      run: pip install -r context/requirements-dev.txt

    - name: Set up Node 12.16.3
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.3'
   
    - name: Install node dependencies
      run: npm ci --prefix context

    - name: Set up git config to make dev-start.sh happy
      run: git config --global submodule.recurse true

    - name: Run test script
      run: ./test.sh
      env:
        GH_ACTIONS_BRANCH: ${{ github.ref }}
        GH_ACTIONS: true
