name: 🐍 Python CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  build:
    # Available versions:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"
          architecture: "x64"
          cache: "pip"
          cache-dependency-path: "context/requirements*.txt"

      - name: Install python main dependencies
        run: pip install -r context/requirements.txt --use-deprecated=legacy-resolver

      - name: Install python dev dependencies
        run: pip install -r context/requirements-dev.txt --use-deprecated=legacy-resolver

      - name: Run test script
        run: etc/test/test-python.sh
